In [58]:
import torch
import torchvision
import numpy as np

Создайте случайный FloatTensor размера 3x4x5
Выведите его форму (shape)

In [74]:
x = torch.DoubleTensor(3, 4, 5)
x.size(), x

(torch.Size([3, 4, 5]),
 tensor([[[ 0.0000e+00, 4.9407e-324, 9.8813e-324, 1.4822e-323, 1.9763e-323],
          [2.4703e-323, 2.9644e-323, 3.4585e-323, 3.9525e-323, 4.4466e-323],
          [4.9407e-323, 5.4347e-323, 5.9288e-323, 6.4229e-323, 6.9169e-323],
          [7.4110e-323, 7.9051e-323, 8.3991e-323, 8.8932e-323, 9.3872e-323]],
 
         [[9.8813e-323, 1.0375e-322, 1.0869e-322, 1.1364e-322, 1.1858e-322],
          [1.2352e-322, 1.2846e-322, 1.3340e-322, 1.3834e-322, 1.4328e-322],
          [1.4822e-322, 1.5316e-322, 1.5810e-322, 1.6304e-322, 1.6798e-322],
          [1.7292e-322, 1.7786e-322, 1.8280e-322, 1.8774e-322, 1.9269e-322]],
 
         [[1.9763e-322, 2.0257e-322, 2.0751e-322, 2.1245e-322, 2.1739e-322],
          [2.2233e-322, 2.2727e-322, 2.3221e-322, 2.3715e-322, 2.4209e-322],
          [2.4703e-322, 2.5197e-322, 2.5691e-322, 2.6185e-322, 2.6680e-322],
          [2.7174e-322, 2.7668e-322, 2.8162e-322, 2.8656e-322, 2.9150e-322]]],
        dtype=torch.float64))

Приведите его к форме 6х10

In [75]:
x = torch.arange(60).view(6,10)
x.size(), x

(torch.Size([6, 10]),
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
         [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]]))

Создайте случайный IntTensor размера 10

In [86]:
y = torch.IntTensor(10)
y.size(), y

(torch.Size([10]),
 tensor([ 544809504, 1869881405,  778593138, 1416916553, 1869835877,  808527986,
         2037275689, 2053731118,  740894821,  740456736], dtype=torch.int32))

Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [87]:
z = torch.mul(x, y)
z


tensor([[           0,   1869881405,   1557186276,   4250749659,   7479343508,
           4042639930,  12223654134,  14376117826,   5927158568,   6664110624],
        [  5448095040,  20568695455,   9343117656,  18419915189,  26177702278,
          12127919790,  32596411024,  34913429006,  13336106778,  14068677984],
        [ 10896190080,  39267509505,  17129049036,  32589080719,  44876061048,
          20213199650,  52969167914,  55450740186,  20745054988,  21473245344],
        [ 16344285120,  57966323555,  24914980416,  46758246249,  63574419818,
          28298479510,  73341924804,  75988051366,  28154003198,  28877812704],
        [ 21792380160,  76665137605,  32700911796,  60927411779,  82272778588,
          36383759370,  93714681694,  96525362546,  35562951408,  36282380064],
        [ 27240475200,  95363951655,  40486843176,  75096577309, 100971137358,
          44469039230, 114087438584, 117062673726,  42971899618,  43686947424]])

Умножьте тензор матрично на себя, чтобы результат был размерности 6x6 Подсказка: .dot может не подойти

In [91]:
w = torch.einsum("ij,kj->ik", z, z)
w.size(), w

(torch.Size([6, 6]),
 tensor([[-3049839759052971186, -7996228032189867766,  5504127768382787270,
            557739495245890690, -4388648777891005890,  9111707022681649146],
         [-7996228032189867766, -2926734277406878774,  2142759477376110218,
           7212253232159099210, -6164997086767463414, -1095503331984474422],
         [ 5504127768382787270,  2142759477376110218, -1218608813630566834,
          -4579977104637243886, -7941345395643920938,  7144030387058953626],
         [  557739495245890690,  7212253232159099210, -4579977104637243886,
           2074536632275964634,  8729050369189173154, -3063179967607169942],
         [-4388648777891005890, -6164997086767463414, -7941345395643920938,
           8729050369189173154,  6952702060312715630,  5176353751436258106],
         [ 9111707022681649146, -1095503331984474422,  7144030387058953626,
          -3063179967607169942,  5176353751436258106, -5030856603229865462]]))

Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [92]:
x=torch.tensor(1.0, requires_grad=True)
z=torch.tensor(0.5, requires_grad=True)
t=torch.tensor(2.0, requires_grad=True)
y = x**3 + z - 75*t
y.backward()
x.grad, z.grad, t.grad

(tensor(3.), tensor(1.), tensor(-75.))

Создайте единичный тензор размера 5x6
Переведите его в формат numpy

In [93]:
q = torch.DoubleTensor(5, 6)
q = q.numpy()
print("X :\n%s\n" % q)
print("X размеры : %s\n" % (q.shape,))
print("X тип : %s\n" % (type(q)))

X :
[[1.10871369e+219 9.24796669e+242 1.28316075e+272 1.78879608e+161
  1.11319007e+171 6.91932170e-072]
 [1.02584502e+200 3.45211702e+175 2.85533142e-109 7.77677062e+160
  3.49340000e+251 5.35841341e+228]
 [1.67772061e+243 5.39192443e+241 6.34915911e+151 1.73429070e+097
  2.43811294e-152 8.02146755e+165]
 [7.09806741e+194 3.02015941e-110 1.35807512e+243 1.21604677e-152
  9.22951563e+135 1.44262360e-105]
 [1.08619036e-153 8.18175267e-085 7.27378071e+175 1.46899930e+179
  9.08367237e+223 1.16466228e-028]]

X размеры : (5, 6)

X тип : <class 'numpy.ndarray'>

